### ISSUE TITLE
Revive this sbt plugin?

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-multi-release-jar#22]
Its looking like Pekko will need multi-release jar's and I just happened to find this. @pjfanning

@eed3si9n Any qualms on this? I guess I would start by cleaning it up (i.e. removing travis and other maintenance work) and then see how much effort it is to get it to work.

**Comment by eed3si9n** [comment]
I think it will be beneficial for the community to revive this effort. The party we might need the blessing is @ktoso who is listed as the maintainer, but I am guessing he'd be happy to see this going.

**Comment by mdedetrich** [comment]
Perfect, just ping me as a heads up when I can start doing the preliminary maintenance work.

**Comment by eed3si9n** [comment]
Created https://github.com/orgs/sbt/teams/sbt-multi-release-jar/members with three of us in it.
One caveat is that as far as I can tell this plugin has never been used?
https://github.com/search?q=sbt-multi-release-jar&type=code

**Comment by mdedetrich** [comment]
> One caveat is that as far as I can tell this plugin has never been used?

Appears so, I guess it never got finished but there shouldn't be any issues with this?

**Comment by ktoso** [comment]
I'm ok with handing over maintenance to someone -- my current employer makes it difficult to be involved in ad-hoc open source projects like this, so it'll be healthier for the project to get someone else lead development. 

It'd be nice if I retained my write rights just in case 🙏

**Comment by mdedetrich** [comment]
@eed3si9n Given that we got the go ahead from @ktoso are there any last steps in getting this going?

**Comment by ktoso** [comment]
Concretely, what do you want to happen here @mdedetrich?

**Comment by mdedetrich** [comment]
Well the first steps would be to do the necessary changes to the plugin so it can work with the latest sbt version along with the customary maintenance steps (i.e. setting up sbt-github-actions, scalafmt, publishing etc etc).

At roughly the same time need to do a cursory exploration into how the plugin works, the intention is to use this for Pekko since a lot of Pekko users are still using JDK8 meaning that at least for now we are stuck with JDK8 as a lowest common denominator and this is hampering us from using runtime features/bigfixes that are exclusing to JDK9 and higher.

**Comment by ktoso** [comment]
Sure, that's "just work" rather than any admin things. So... just do it 😉 
As I mentioned, I can't contribute open source code here, so it'll be up to y'all.

Anything you want from me here?
Who needs to get write access, Eugene has it I think.

**Comment by mdedetrich** [comment]
> Sure, that's "just work" rather than any admin things. So... just do it 😉 As I mentioned, I can't contribute open source code here, so it'll be up to y'all.

Indeed

> Anything you want from me here? Who needs to get write access, Eugene has it I think.

Maybe not now, but later on when I get more familiar with the codebase there may be some questions that need answering.

> Who needs to get write access, Eugene has it I think.

Thats what I was pertaining to earlier, need to get some admins/write access on this project so we can get PR's rolling through so we can kickstart this.

**Comment by eed3si9n** [comment]
Like I mentioned, I've already created https://github.com/orgs/sbt/teams/sbt-multi-release-jar. Feel free to start sending PRs.

**Comment by mdedetrich** [comment]
> Like I mentioned, I've already created https://github.com/orgs/sbt/teams/sbt-multi-release-jar. Feel free to start sending PRs.

Apologies must have missed/forgotten this, had a lot going on past month.

I'll start working on it soon

**Comment by mdedetrich** [comment]
@eed3si9n I think this can be closed?
