### ISSUE TITLE
Change base branch from `master` to `main`

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-multi-release-jar#28]
i.e. https://github.com/github/renaming#renaming-existing-branches

@eed3si9n I don't have permissions to do this. Best to do this now because future PR's will make references to the base branch in the actual code i.e. scalafmt/sbt-github-actions etc etc (plus I don't think many people have actually cloned this repo yet) so its best to change it to `main` to avoid making a rod for our own back

**Comment by eed3si9n** [comment]
Done!
