### ISSUE TITLE
Fix maintainer section in README.md

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-multi-release-jar#37]
https://github.com/sbt/sbt-multi-release-jar?tab=readme-ov-file#maintainer

Not sure what language you want to use, I assume its meant to be something like "maintained by sbt plugin maintainers" (hence why I am assigning the issue to you).

**Comment by eed3si9n** [comment]
I guess we can link to [sbt-multi-release-jar maintainers](https://github.com/orgs/sbt/teams/sbt-multi-release-jar) and drop specific names and companies?
